name: CI
on: [push]
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install dependencies
        run: npm i
      - name: Run linters
        run: npm run check
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
        env:
          REACT_APP_ACCU_WEATHER_API_KEY: ${{ secrets.REACT_APP_ACCU_WEATHER_API_KEY }}
          REACT_APP_DARK_SKY_API_KEY: ${{ secrets.REACT_APP_DARK_SKY_API_KEY }}
          REACT_APP_GOOGLE_MAP_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAP_API_KEY }}
          REACT_APP_UNSPLASH_API_ENDPOINT: ${{ secrets.REACT_APP_UNSPLASH_API_ENDPOINT }}
          REACT_APP_WEATHER_BIT_API_KEY: ${{ secrets.REACT_APP_WEATHER_BIT_API_KEY }}
      - name: Save coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
      - name: Upload coverage report to Codecov
        run: npm run codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
